// CFS Terminal Operating System - Database Schema

import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

// Users table for authentication
export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  role: text("role").notNull().default("operator"),
  passwordHash: text("password_hash"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  lastLogin: integer("last_login", { mode: "timestamp" }),
});

// Containers table
export const containers = sqliteTable("containers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  containerNo: text("container_no").notNull().unique(),
  blNo: text("bl_no").notNull(),
  size: text("size").notNull(),
  type: text("type").notNull(),
  status: text("status").notNull(),
  yardLocation: text("yard_location"),
  row: integer("row"),
  bay: integer("bay"),
  tier: integer("tier"),
  weight: real("weight"),
  tare: real("tare"),
  grossWeight: real("gross_weight"),
  shipper: text("shipper"),
  consignee: text("consignee"),
  commodity: text("commodity"),
  portOfLoading: text("port_of_loading"),
  portOfDischarge: text("port_of_discharge"),
  arrivalDate: text("arrival_date"),
  freeTime: integer("free_time"),
  daysInYard: integer("days_in_yard"),
  customsStatus: text("customs_status"),
  iceGateRef: text("icegate_ref"),
  beNo: text("be_no"),
  igmNo: text("igm_no"),
  lineNo: text("line_no"),
  vesselName: text("vessel_name"),
  voyageNo: text("voyage_no"),
  sealNo: text("seal_no"),
  temperature: real("temperature"),
  isHazmat: integer("is_hazmat", { mode: "boolean" }).default(false),
  imoClass: text("imo_class"),
  unNo: text("un_no"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Trucks table
export const trucks = sqliteTable("trucks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  truckNo: text("truck_no").notNull().unique(),
  driverName: text("driver_name"),
  driverLicense: text("driver_license"),
  driverMobile: text("driver_mobile"),
  transporterName: text("transporter_name"),
  transporterCode: text("transporter_code"),
  tokenNo: text("token_no"),
  tokenStatus: text("token_status"),
  truckStatus: text("truck_status"),
  gateInTime: text("gate_in_time"),
  gateOutTime: text("gate_out_time"),
  purpose: text("purpose"),
  weighbridgeWeight: real("weighbridge_weight"),
  tareWeight: real("tare_weight"),
  netWeight: real("net_weight"),
  appointmentTime: text("appointment_time"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Truck Tokens table
export const tokens = sqliteTable("tokens", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  tokenNo: text("token_no").notNull().unique(),
  truckNo: text("truck_no").notNull(),
  driverName: text("driver_name"),
  transporterName: text("transporter_name"),
  issuedAt: text("issued_at"),
  validUntil: text("valid_until"),
  status: text("status").notNull(),
  purpose: text("purpose"),
  containerNos: text("container_nos"),
  qrCode: text("qr_code"),
  gateAssigned: text("gate_assigned"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Gate Entries table
export const gateEntries = sqliteTable("gate_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  gateNo: text("gate_no").notNull(),
  gateType: text("gate_type").notNull(),
  truckNo: text("truck_no").notNull(),
  tokenNo: text("token_no"),
  driverName: text("driver_name"),
  entryTime: text("entry_time"),
  exitTime: text("exit_time"),
  containerNos: text("container_nos"),
  status: text("status").notNull(),
  operatorId: text("operator_id"),
  remarks: text("remarks"),
  qrScanned: integer("qr_scanned", { mode: "boolean" }).default(false),
  weighbridgeSlip: text("weighbridge_slip"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Weighbridge Records table
export const weighbridgeRecords = sqliteTable("weighbridge_records", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slipNo: text("slip_no").notNull().unique(),
  truckNo: text("truck_no").notNull(),
  driverName: text("driver_name"),
  grossWeight: real("gross_weight"),
  tare: real("tare"),
  netWeight: real("net_weight"),
  weighedAt: text("weighed_at"),
  operatorId: text("operator_id"),
  containerNo: text("container_no"),
  purpose: text("purpose"),
  vehicleType: text("vehicle_type"),
  remarks: text("remarks"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Invoices table
export const invoices = sqliteTable("invoices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  invoiceNo: text("invoice_no").notNull().unique(),
  invoiceDate: text("invoice_date"),
  dueDate: text("due_date"),
  status: text("status").notNull(),
  billToName: text("bill_to_name"),
  billToAddress: text("bill_to_address"),
  billToGstin: text("bill_to_gstin"),
  billToPan: text("bill_to_pan"),
  billToEmail: text("bill_to_email"),
  billToPhone: text("bill_to_phone"),
  billFromName: text("bill_from_name"),
  billFromAddress: text("bill_from_address"),
  billFromGstin: text("bill_from_gstin"),
  billFromPan: text("bill_from_pan"),
  billFromCin: text("bill_from_cin"),
  containerNo: text("container_no"),
  blNo: text("bl_no"),
  subtotal: real("subtotal"),
  cgst: real("cgst"),
  sgst: real("sgst"),
  igst: real("igst"),
  total: real("total"),
  sacCode: text("sac_code"),
  placeOfSupply: text("place_of_supply"),
  currency: text("currency").default("INR"),
  paymentTerms: text("payment_terms"),
  bankName: text("bank_name"),
  accountNo: text("account_no"),
  ifsc: text("ifsc"),
  branch: text("branch"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ICEGATE Entries table
export const icegateEntries = sqliteTable("icegate_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  beNo: text("be_no").notNull(),
  beDate: text("be_date"),
  igmNo: text("igm_no"),
  igmDate: text("igm_date"),
  lineNo: text("line_no"),
  containerNo: text("container_no"),
  blNo: text("bl_no"),
  importerName: text("importer_name"),
  importerIec: text("importer_iec"),
  importerGstin: text("importer_gstin"),
  customsStation: text("customs_station"),
  assessedValue: real("assessed_value"),
  dutyAmount: real("duty_amount"),
  status: text("status").notNull(),
  examOrder: text("exam_order"),
  oocDate: text("ooc_date"),
  chaName: text("cha_name"),
  chaCode: text("cha_code"),
  commodity: text("commodity"),
  hsCode: text("hs_code"),
  quantity: real("quantity"),
  unit: text("unit"),
  currency: text("currency"),
  cif: real("cif"),
  exchangeRate: real("exchange_rate"),
  remarks: text("remarks"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Delivery Orders table
export const deliveryOrders = sqliteTable("delivery_orders", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  doNo: text("do_no").notNull().unique(),
  doDate: text("do_date"),
  validUntil: text("valid_until"),
  status: text("status").notNull(),
  doType: text("do_type").notNull(),
  containerNo: text("container_no"),
  blNo: text("bl_no"),
  beNo: text("be_no"),
  igmNo: text("igm_no"),
  lineNo: text("line_no"),
  consigneeName: text("consignee_name"),
  consigneeGstin: text("consignee_gstin"),
  consigneeAddress: text("consignee_address"),
  consigneeContact: text("consignee_contact"),
  chaName: text("cha_name"),
  chaCode: text("cha_code"),
  chaContact: text("cha_contact"),
  shippingLine: text("shipping_line"),
  shippingLineRef: text("shipping_line_ref"),
  commodity: text("commodity"),
  containerSize: text("container_size"),
  containerType: text("container_type"),
  grossWeight: real("gross_weight"),
  packages: integer("packages"),
  packageUnit: text("package_unit"),
  yardLocation: text("yard_location"),
  vesselName: text("vessel_name"),
  voyageNo: text("voyage_no"),
  portOfLoading: text("port_of_loading"),
  customsOocDate: text("customs_ooc_date"),
  dutyPaid: integer("duty_paid", { mode: "boolean" }).default(false),
  dutyAmount: real("duty_amount"),
  demurrageCleared: integer("demurrage_cleared", { mode: "boolean" }).default(false),
  demurrageAmount: real("demurrage_amount"),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  releasedBy: text("released_by"),
  releasedAt: text("released_at"),
  truckNo: text("truck_no"),
  tokenNo: text("token_no"),
  remarks: text("remarks"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// Activity Log table for tracking changes
export const activityLogs = sqliteTable("activity_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  entityType: text("entity_type").notNull(),
  entityId: integer("entity_id").notNull(),
  action: text("action").notNull(),
  userId: integer("user_id"),
  userName: text("user_name"),
  details: text("details"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
